apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elk
spec:
  selector:
    name: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: cont
    - protocol: TCP
      port: 9300
      targetPort: 9300
      name: external
